language: d
sudo: false

matrix:
    include:
        - d: dmd-2.083.1
        - d: dmd-2.082.1
        - d: dmd-2.081.2
        - d: dmd-2.080.1
        - d: dmd-2.079.0
        - d: ldc-1.12.0
        - d: ldc-1.11.0
        - d: ldc-1.10.0

script:
  - pushd examples/sdl  && dub build --compiler=${DC} && popd
  - pushd examples/arsd && dub build --compiler=${DC} && popd